name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-althea-dash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: yarn && yarn build
  test-althea-dash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: yarn && yarn test
